# Generated by Django 5.1.8 on 2025-04-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_alter_customuser_name_alter_identity_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='name',
        ),
    ]
