# Generated by Django 5.1.8 on 2025-04-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_country_name_alter_state_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='name',
        ),
        migrations.RemoveField(
            model_name='state',
            name='name',
        ),
    ]
