# Generated by Django 5.1.8 on 2025-04-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_country_name_remove_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
